[build]
  publish = "frontend/expense-tracker/dist"
  command = "cd frontend/expense-tracker && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "backend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200